name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Bug Fixes'
    labels: ['fix', 'bug']
  - title: '🧰 Maintenance'
    labels: ['chore', 'dependencies', 'documentation']
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
category-template: '### $TITLE'
version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor']
  patch:
    labels: ['patch']
  default: patch
template: |
  ## What Changed

  $CHANGES